### ISSUE TITLE
default ingress proxy-body-size must be expected smaller than allowed payload size for api calls

### ISSUE THREAD

**Issue by SchuhMichael** [apache/openwhisk-deploy-kube#509]
In helm/openwhisk/values.yaml, this default for annotations would help to avoid problems:

```
whisk:
  ingress:
    apiHostName: "alias-to-k8s-ingress.domain"
    apiHostPort: 433    apiHostProto: "https"
    type: Standard
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
```

Without this annotation, in #506  I cannot run  helm/openwhisk/configMapFiles/installPackages/myTask.sh, because helm/openwhisk/configMapFiles/installPackages/myTask.sh calls /openwhisk/ansible/roles/routemgmt/files/installRouteMgmt.sh which fails every time. This operation  has a comment in myTask.sh that it has known problems. 

```
    # This operation is unreliable in a TravisCI environment (for unknown reasons),
    # so try multiple times before giving up.
```

I manually ran the commands and observed an HTTP 413 error that appears when the script calls action update with the first zipfile openwhisk/core/routemgmt/getApi/getApi.zip, which is a bit more than 2MB in size. 

```
echo Installing apimgmt actions
$WSK_CLI -i --apihost "$APIHOST" action update --auth "$AUTH" "$NAMESPACE/apimgmt/getApi" "$OPENWHISK_HOME/core/routemgmt/getApi/getApi.zip" \
-a description 'Retrieve the specified API configuration (in JSON format)' \
--kind nodejs:default \
-a web-export true -a final true
```

With the frontdoor-ingress in default settings, this payload is too large and every attempt receives an HTTP413 error as response. The install-packages job finally fails.  

With the annotation in the first code block, it runs. I have not tested it this default setting is compatible for other modes of whisk.ingress.type. If it cannot be a default, maybe this should be a part of the documentation.
