### ISSUE TITLE
EKS Non Self Signed Certs not applied to ingress

### ISSUE THREAD

**Issue by buggtb** [apache/openwhisk-deploy-kube#580]
```
whisk:
  ingress:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-<>:certificate/<>
  limits:
    actions:
      time:
        std: "3m"
        max: "60m"
  podtemplate: file:/tmp/action-pod-template.yml
```

So I have the above setup and when I deploy it the annotations don't appear in the nginx service.

But if I paste them in, then the SSL stuff mostly works, although I needed a few more tweaks:

```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:<>:certificate/<>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https-api

```
also down in the port spec I had to update the https-api port:

```
  - name: https-api
    nodePort: 31068
    port: 443
    protocol: TCP
    targetPort: http

```

otherwise it would complain about sending a http request to the https port, although that might just be something I've misconfigured I guess.
