### ISSUE TITLE
whisk.ingress.type for "Standard" doesn't work

### ISSUE THREAD

**Issue by ningyougang** [apache/openwhisk-deploy-kube#617]
mycluster.yaml is 
```
whisk:
  ingress:
    type: Standard
    apiHostName: xxx.xxx.xxx.xxx
    apiHostPort: 31001

nginx:
  httpsNodePort: 31001
```
After execute `helm install ./helm/openwhisk --namespace=openwhisk --generate-name -f mycluster.yaml`, found 
```
openwhisk-1593667523-install-packages-487dk              0/1     Error       0          6m4s
openwhisk-1593667523-install-packages-ptkgb              0/1     Error       0          11m
openwhisk-1593667523-install-packages-qchfc              0/1     Error       0          8m10s
```
I checked deeply, 
```
kubectl describe ingress openwhisk-1593667523-ingress -n openwhisk
...
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
...
```
reported key error log: `error: endpoints "default-http-backend" not found`

It seems need to create `default-http-backend` by myself: https://github.com/kubernetes/ingress-nginx/issues/5525#issuecomment-645817850

Someone konw about it? (I checked, it seems need to lack` ingress controller` and relative service here )
