### ISSUE TITLE
wsk cli timeout when trying to connect to ELB on AWS EKS

### ISSUE THREAD

**Issue by antomor** [apache/openwhisk-deploy-kube#628]
Hi,
 I have followed step-by-step the procedure required to deploy OpenWhisk on AWS, but although all the components of the system (pods, services, etc..) seem properly running (any error raised), I am not able to deploy any function. After setting the apihost on the `wsk cli`, if I run the command `wsk -i property get`, I get the following error:
```
error: Unable to obtain API build information: Get https://internal-***************.eu-central-1.elb.amazonaws.com:443/api/v1: dial tcp 192.168.154.239:443: i/o timeout
```
I have also executed the `helm` tests successfully. Before deploying to AWS, I have already deployed OpenWhisk locally with `kind`, and it worked like a charm.

Any idea would be appreciated.

**Comment by antomor** [comment]
I solved by using the configuration [suggested](https://github.com/apache/openwhisk-deploy-kube/blob/master/docs/k8s-aws.md#configuring-openwhisk-using-ssl-and-elastic-loadbalancers), even if, in my case, I was using a self-signed certificate (for testing-purpose only):
```
whisk:
  ingress:
    awsSSL: "true"
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https-api
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <arn:aws:iam::server-certificate>
```
