### ISSUE TITLE
Allow specifying update strategy "Recreate" for deployments with PVs

### ISSUE THREAD

**Issue by travigd** [apache/openwhisk-deploy-kube#638]
Some cloud providers (GCE in my case) don't support RWM disks, which means that rolling updates fail (since the new pod can't attach the PD).

The couchdb and redis pods (since they're `Deployment`s) should support
```yaml
spec:
  ...
  strategy:
    type: "Recreate"
  ...
```
