### ISSUE TITLE
Cannot create cluster; joining worker node failed

### ISSUE THREAD

**Issue by Sayeed42** [apache/openwhisk-deploy-kube#656]
I am running kind version 0.9.0 on CentOS 8. The command `kind create cluster` works fine. But, when I try to execute `kind create cluster --config kind-cluster.yaml` it fails to join worker nodes. Is there anything I am doing wrong?
![image](https://user-images.githubusercontent.com/57699207/101084908-a5465980-357c-11eb-8139-9c0cf4d5aaef.png)

**Comment by dgrove-oss** [comment]
Whats the contents of your kind-cluster.yaml?

**Comment by Sayeed42** [comment]
It was as given in the kind setup instructions. Here it is:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - hostPort: 31001
      containerPort: 31001
- role: worker
```
