### ISSUE TITLE
Request: Clarify how to change default auth in helm chart 

### ISSUE THREAD

**Issue by gnoejuan** [apache/openwhisk-deploy-kube#718]
I apologize if the documentation already exists. I have tried searching already, and haven't found it.

 ```yaml
 # Production deployments _MUST_ override these default auth values
  auth:
    system: "789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
    guest: "23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
```

These reminds me of htpassword, but in my expierence it would be more along the lines of 

system:faskjdflkasdbfasdf. 

So I'm not confident with my assumption.

Could I receive assistance?
