### ISSUE TITLE
"wsk api list" NOAUTH Authentication required

### ISSUE THREAD

**Issue by SidMorad** [apache/openwhisk-deploy-kube#736]
First I thought this might be a [apigateway issue](https://github.com/apache/openwhisk-apigateway/issues/395) but then I found [this issue](https://github.com/apache/openwhisk-deploy-kube/issues/104) with some similarities and hints.

Here are my configs and outputs:
_values.yaml_
```
whisk:
  ingress:
    type: LoadBalancer
    apiHostName: "wsk.mydomain.com"
    apiHostPort: 80
    apiHostProto: "http"
    useInternally: false
```
_wsk-whisk.config_ k8s ConfigMap
```
data:
  whisk_api_host_name: wsk-nginx.wsk.svc.cluster.local
  whisk_api_host_nameAndPort: wsk-nginx.wsk.svc.cluster.local:443
  whisk_api_host_port: "443"
  whisk_api_host_proto: https
  whisk_api_host_url: https://wsk-nginx.wsk.svc.cluster.local:443
  whisk_cli_version_tag: 1.1.0
  whisk_info_buildNo: v1.0.0:20201020a
  whisk_info_date: 2020-10-20-01:00:00Z
  whisk_system_namespace: /whisk.system
```
_wsk package list_
```
packages
/whisk.system/messagingWeb                                             private
/whisk.system/messaging                                                shared
/whisk.system/alarmsWeb                                                private
/whisk.system/alarms                                                   shared
/whisk.system/slack                                                    shared
/whisk.system/websocket                                                shared
/whisk.system/weather                                                  shared
/whisk.system/utils                                                    shared
/whisk.system/samples                                                  shared
/whisk.system/github                                                   shared
/whisk.system/apimgmt                                                  private
```
_wsk action list /whisk.system/apimgmt_
```
actions
/whisk.system/apimgmt/deleteApi                                        private nodejs:10
/whisk.system/apimgmt/createApi                                        private nodejs:10
/whisk.system/apimgmt/getApi                                           private nodejs:10
```
_wsk api list_
```
error: Unable to obtain the API list: Unable to obtain API(s) from the API Gateway (status code 500):
 {"status":500,"message":"Error: Failed to retrieve APIs: NOAUTH Authentication required."}
```

@dgrove-oss would you please be helpful on this issue too? :) I will be happy to try any suggestions and provide more information to help resolving this issue.

p.s. I did comment `whisk.ingress` overrides to use default values, but outputs didn't change.
