### ISSUE TITLE
EKS deployment does not accept https requests, only http

### ISSUE THREAD

**Issue by ferancona** [apache/openwhisk-deploy-kube#745]
## Steps to reproduce the issue
1. Create EKS cluster: `eksctl create cluster --name test-cluster-1 --region eu-central-1 --node-type t2.large --nodes 1`
2. Label nodes: `kubectl label nodes --all openwhisk-role=invoker`
3. Install Helm chart: `helm install owdev openwhisk-deploy-kube/helm/openwhisk -n openwhisk --create-namespace -f mycluster.yaml`
4. Setup WSK CLI as the [docs ](https://github.com/apache/openwhisk-deploy-kube#configure-the-wsk-cli) say, using the load balancer's DNS: `wsk -i property set --apihost https://<load-balancer-DNS>:443`
5. Run WSK command: `wsk list -v`

## Observations
* Output of `wsk list -v`: 
![image](https://user-images.githubusercontent.com/31116930/185684271-f9f3954a-9a5c-40a5-a0fa-f18b3e7ceb2d.png)
* Load balancer's info from AWS Console:
![image](https://user-images.githubusercontent.com/31116930/185683692-b7709ff2-d2d0-4f0f-8bef-dfda8209e392.png)
* Api calls work when setting up the WSK CLI using http instead of https.

### mycluster.yaml
```yaml
k8s:
  persistence:
    enabled: false

whisk:
  ingress:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::XXXXXXXXXXXX:server-certificate/ow-self-signed

whisk:
  ingress:
    awsSSL: "true"
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https-api
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:XXXXXXXXXXXX:certificate/YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY # AWS Certificate Manager (ow-self-signed).
```

## Reason of interest
I want to use the OpenWhisk deployment as an endpoint for *AWS EventBridge*, but currently it is only possible to add *API Destinations* that use https endpoints.
