### ISSUE TITLE
No startup as zookeeper pods readiness probe failes

### ISSUE THREAD

**Issue by Xnyle** [apache/openwhisk-deploy-kube#756]
Openwhisk doesn't start up for me, reason is that zookeepers readiness is always failing. 

As long as it's failing, no DNS record for the headless service is being created and startup of other services never continues.

The way zookepers probe is currently defined it results in the following statement:

bash '-c' echo ruok | nc -w 1 localhost 2181 | grep imok

How is that supposed to even work? 

bash '-c' 'echo ruok' | nc -w 1 localhost 2181 | grep imok

Would work, still ugly.

**Comment by Xnyle** [comment]
I guess the DNS record is correct should work but maybe it's because the pods readyness probe fails. The way zookepers probe is defined that would result in the following statement:

bash -c echo ruok | nc -w 1 localhost 2181 | grep imok

but how is that supposed to even work? the pipe is outside of bash -c and bash -c just returns an empty string, thus the response is not imok, thus grep fails.

**Comment by dgrove-oss** [comment]
Note how it is defined in zookeeper-pod.yaml:
```
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "echo ruok | nc -w 1 localhost {{ .Values.zookeeper.port }} | grep imok"
```
