### ISSUE TITLE
Changing the nginx httpsPort does not expose the REST API

### ISSUE THREAD

**Issue by jhawarchirag0** [apache/openwhisk-deploy-kube#770]
I modified the kubernetes deployment to be exposed to a different port than the default 443 port as another service is already using that port. When I try to deploy this to an external IP, I am unable to reach the https://<external ip>:31001/api/v1/
```
# Nginx configurations
nginx:
  imageName: "nginx"
  imageTag: "1.19"
  imagePullPolicy: "IfNotPresent"
  replicaCount: 1
  restartPolicy: "Always"
  httpPort: 80
  httpsPort: 4430
  httpsNodePort: 31001
  certificate:
    external: false
    cert_file: ""
    key_file: ""
    sslPassword: ""
```

The same works when the targetPort is set to 443 and port is set to 4430
